version: '3.8'

services:
  trudesk:
    image: trudesk-custom:latest
    build: .
    restart: always
    ports:
      - "8118:8118"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
      ELASTICSEARCH_URI: "http://elasticsearch:9200"
      INTERNAL_SERVICE_KEY: "trudesk-internal-service-2024"
    volumes:
      - trudesk_uploads:/usr/src/trudesk/public/uploads
      - trudesk_backups:/usr/src/trudesk/backups
    depends_on:
      - mongo
      - elasticsearch

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  trudesk_uploads:
  trudesk_backups:
  mongo_data:
  elasticsearch_data: